### ISSUE TITLE
import_module error

### ISSUE THREAD

**Issue by JACKYLUO1991** [zju3dv/mlp_maps#1]
No such file or directory: '/tmp/tmpzweapbc7/tmp7r1yko1j.py' appears when loading import_module library.

**Comment by pengsida** [comment]
Which command you used?

**Comment by JACKYLUO1991** [comment]
python run.py --config configs/zjumocap/dymap_313.py mode visualize vis_novel_view True fixed_time True fast_render True

**Comment by pengsida** [comment]
Please list the complete error message.

**Comment by JACKYLUO1991** [comment]
![image](https://user-images.githubusercontent.com/21237742/226507209-8ee8317e-966a-4380-8c9f-422ec9c7470f.png)

**Comment by yunzhiy** [comment]
Hi. I run the command and there is no such problem.  Maybe you can check your code because there is no --cfg argument in run.py.

**Comment by pengsida** [comment]
It is quite strange. Because the code won't print the usage message.

**Comment by JACKYLUO1991** [comment]
@yunzhiy @pengsida Thanks for the reply, I probably know what's going on, there should be a conflict between the libraries.

**Comment by pengsida** [comment]
Could you describe the conflict in more details? Thank you.

**Comment by JACKYLUO1991** [comment]
@pengsida This is my problem, running the code in the base environment without switching to mlp's environment.

**Comment by pengsida** [comment]
@JACKYLUO1991 Thank you!

**Comment by JACKYLUO1991** [comment]
@pengsida When running the training post-processing script it shows no dymap_mesh_dataset.py file.

**Comment by pengsida** [comment]
Which command you used?

**Comment by JACKYLUO1991** [comment]
@pengsida 
![image](https://user-images.githubusercontent.com/21237742/228111850-0db08cd1-846d-4edd-b024-72e66057d837.png)
This one.

**Comment by yunzhiy** [comment]
hi. I have fixed the bug and you can try it again.

**Comment by JACKYLUO1991** [comment]
@yunzhiy Many thanks.
