### ISSUE TITLE
No MLPs for density?

### ISSUE THREAD

**Issue by mra-h** [zju3dv/mlp_maps#12]
Hi,

In the paper you say you MLPs to predict both color and densities. However, when predicting densities in the code, no MLP is queried?

[Here](https://github.com/zju3dv/mlp_maps/blob/7fda4ac19e84692f1070614f669e44080541bf2b/lib/networks/dymap.py#L53) there are only keys in the dictionary for color and no keys for densities/color. In fact [`multikn_forward`](https://github.com/zju3dv/mlp_maps/blob/7fda4ac19e84692f1070614f669e44080541bf2b/lib/networks/dymap.py#L187) is only called to predict RGB values. Why is this the reason?

Thanks!

**Comment by pengsida** [comment]
The density layer is implemented as an one-layer MLP, which is simply a matrix multiplication.
