### ISSUE TITLE
re-produced training ok, but Error(s) in loading state_dict for Network 

### ISSUE THREAD

**Issue by PeterFWS** [zju3dv/mlp_maps#14]
Hello,

Thanks for your great work, 

I have trained your network on dataset NHR/sport1 myself.
However, when I try to load the checkpoint, there is a loading error:

``
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Network:
	Missing key(s) in state_dict: "encodings", "occupancy_grids". 
	Unexpected key(s) in state_dict: "latent_vectors.down1.0.0.weight", "latent_vectors.down1.0.0.bias", "latent_vectors.down1.0.1.weight", "latent_vectors.down1.0.1.bias", "latent_vectors.down1.0.2.weight", "latent_vectors.down1.0.2.bias", "latent_vectors.down1.0.3.weight", "latent_vectors.down1.0.3.bias", "latent_vectors.down1.0.4.weight", "latent_vectors.down1.0.4.bias", "latent_vectors.down1.0.5.weight", "latent_vectors.down1.0.5.bias", "latent_vectors.down1.0.6.weight", "latent_vectors.down1.0.6.bias", "latent_vectors.down1.1.0.weight", "latent_vectors.down1.1.0.bias", "latent_vectors.down1.1.1.weight", "latent_vectors.down1.1.1.bias", "latent_vectors.down1.1.2.weight", "latent_vectors.down1.1.2.bias", "latent_vectors.down1.1.3.weight", "latent_vectors.down1.1.3.bias", "latent_vectors.down1.1.4.weight", "latent_vectors.down1.1.4.bias", "latent_vectors.down1.1.5.weight", "latent_vectors.down1.1.5.bias", "latent_vectors.down1.1.6.weight", "latent_vectors.down1.1.6.bias", "latent_vectors.down1.2.0.weight", "latent_vectors.down1.2.0.bias", "latent_vectors.down1.2.1.weight", "latent_vectors.down1.2.1.bias", "latent_vectors.down1.2.2.weight", "latent_vectors.down1.2.2.bias", "latent_vectors.down1.2.3.weight", "latent_vectors.down1.2.3.bias", "latent_vectors.down1.2.4.weight", "latent_vectors.down1.2.4.bias", "latent_vectors.down1.2.5.weight", "latent_vectors.down1.2.5.bias", "latent_vectors.down1.2.6.weight", "latent_vectors.down1.2.6.bias", "latent_vectors.down2.weight", "latent_vectors.down2.bias", "latent_vectors.mu.weight", "latent_vectors.mu.bias", "latent_vectors.logstd.weight", "latent_vectors.logstd.bias". 
``

There was no problem loading the pre-trained checkpoint provided by you.
I am very appreciative if you have any feedback about this.

Best regards,

**Comment by pengsida** [comment]
It seems that you used an incorrect command. Which command did you used?

**Comment by PeterFWS** [comment]
python run.py --config configs/nhr/sport1.py mode evaluate fast_render True

**Comment by PeterFWS** [comment]
Oh, sorry,

I forget to post-process the trained model.

Now everything is working.

Thanks.
