### ISSUE TITLE
Unexpected error while running the code

### ISSUE THREAD

**Issue by andy-neparidze** [zju3dv/mlp_maps#19]
I ran into an unexpected problem.

I installed everything according to INSTALL.md and README.md instructions and had no errors during installation.

But when I run the code using the NHR dataset, the code throws an exception that you can see in the attached screenshot below:
![Screenshot from 2023-08-15 11-17-51](https://github.com/zju3dv/mlp_maps/assets/101195678/103e39aa-18fd-4476-8ee9-29b285310fdb)

I would very much appreciate any tip or guidance you can provide on how to solve this.

**Comment by pengsida** [comment]
Please check the cuda version.
