### ISSUE TITLE
how fit SMPL vertices to all views

### ISSUE THREAD

**Issue by ch1998** [zju3dv/mlp_maps#22]
I tested your work, it works great, and I want to know how to make custom data.

I used the model to export the vertices of SMPL but it cannot be projected correctly on each view.

The projection result is as follows
![image](https://github.com/zju3dv/mlp_maps/assets/37291486/21cb0c97-1973-40fa-886f-8598060a744a)

how to get the transform matrix  like in sport1.py

**Comment by pengsida** [comment]
You could follow this instruction: https://vcl3d.github.io/VolumetricCapture/

**Comment by ch1998** [comment]
Thank you, I will try it
