### ISSUE TITLE
Questions about how to make your own dataset

### ISSUE THREAD

**Issue by yanmie-1122** [zju3dv/mlp_maps#24]
Thanks for your great work!
I would like to use your method to train my own model, but I am not clear how to process the data from the initial video into a data format similar to the processed NHR you provided. Now I have tried, but I still hope you can provide a more comprehensive suggestion or solution?
Your advice or explanation will be very helpful to me. Thank you very much

**Comment by pengsida** [comment]
Thank you for your interest. We will prepare a tutorial on making our own dataset.

**Comment by pengsida** [comment]
See this: https://github.com/zju3dv/im4d/blob/main/docs/custom_data_tutorial.md
