### ISSUE TITLE
kilonerf_cuda's ImportError

### ISSUE THREAD

**Issue by AlfredMarcel** [zju3dv/mlp_maps#4]
Thanks for your contribution!
When I run your code, something weird happen.

![QQ截图20230331231715](https://user-images.githubusercontent.com/49266277/229160951-04495364-cd7a-4bee-b165-bc7272ab2618.png)

It seems like kilonerf_cuda is not installed, but my device shows that the installation is successful.

![QQ截图20230331231827](https://user-images.githubusercontent.com/49266277/229161477-24835baf-c81a-440f-a0a8-5e991362136d.png)

Help me please... TAT

**Comment by yunzhiy** [comment]
I think it's due to the libglut library not being installed successfully.  You can try `sudo apt-get install freeglut3` to install the package.

**Comment by AlfredMarcel** [comment]
It works! Thank you!!!
