### ISSUE TITLE
CUDA error [ No Kernel images~]

### ISSUE THREAD

**Issue by swanilee** [zju3dv/mlp_maps#8]
Hello!

First, thanks for your contribution.
To run the "train_net.py" code,
I met this error in several times.
Then, I don't know what is the problem.

![image](https://github.com/zju3dv/mlp_maps/assets/26716759/4e2114ee-9922-47b9-997f-cc183290e83c)

I don't know exactly what is the problem..

anaconda in docker container.
python==3.8.16
pytorch ==1.12.1+cu113
cuda version (when i use nvcc- V) :  cuda_11.3.r11.3 (11.3)
Tesla v100

I would be grateful if you could help me.

Thank you

**Comment by mra-h** [comment]
@swanilee Did you manage to solve this problem?

**Comment by swanilee** [comment]
@mra-h Not yet, I think that this is architecture version conflict problem.

**Comment by pengsida** [comment]
Maybe you need to compile the KiloNeRF module instead of installing the pre-compiled one.

**Comment by PeterFWS** [comment]
hi, this problem can be solved by running command: 
**TORCH_CUDA_ARCH_LIST="6.0 7.0 7.5 8.0 8.6+PTX" python setup.py develop** 
when you compile KiloNeRF's C++/CUDA code. 

Add the GPU Compute Capability accordingly, look at https://developer.nvidia.com/cuda-gpus.
