### ISSUE TITLE
Typo in requirements.txt

### ISSUE THREAD

**Issue by MikePelton** [zju3dv/mlp_maps#9]
Hi - thanks for this phenomenal piece of work. There's a wee typo I think: "requirements.txt" references "pymcudes", pretty sure that should be "pymcubes"?

**Comment by swanilee** [comment]
I've solved the problem, so I'm leaving a comment to help.

To install "pymcubes", do 
`$ pip install --upgrade PyMCubes`

( Ref. https://github.com/pmneila/PyMCubes )

**Comment by yunzhiy** [comment]
Thank you for pointing out the existing errors and I have updated "requirements.txt".
